- hosts: localhost
  connection: local

  vars:

    homebrew_cask_packages:
      - name: docker
      - name: sourcetree
      - name: iterm2
      - name: slack
      - name: google-japanese-ime
      - name: firefox
      - name: visual-studio-code
      - name: dropbox

    homebrew_packages:
      - name: zsh
      - name: git
      - name: tree
      - name: nkf
      - name: sqlite
      - name: jq
      - name: gdrive
      - name: github/gh/gh
      - name: reattach-to-user-namespace
      - name: vim
      - name: tig
      - name: ghq
      - name: peco
      - name: packer

    pip_packages:
      - name: sqlparse

  tasks:
    - name: homebrew update/upgrade
      # brew updateはHomebrewのアップデートのみ行うのに対して、brew upgradeではHomebrewのアップデートに加えてHomebrewでインストールしたパッケージのアップデートも行う
      homebrew:
        update_homebrew: yes
        upgrade_all: yes

    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      # ※1 GUIツールをインストールする場所を `/Application` に固定
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    - name: Python 3.8 install some packages (not virtualenv)
      pip:
        name: '{{ item.name }}'
        executable: pip3.8
      with_items: '{{ pip_packages }}'

