- hosts: localhost
  connection: local

  vars:

    homebrew_cask_packages:
      - name: docker
      - name: sourcetree
      - name: iterm2
      - name: slack
      - name: google-japanese-ime
      - name: firefox
      - name: visual-studio-code

    homebrew_packages:
      - name: git
      - name: tree
      - name: nkf
      - name: sqlite
      - name: jq
      - name: gdrive
      - name: mysql --client-only
      - name: reattach-to-user-namespace
      - name: vim
      - name: tig
      - name: ghq
      - name: peco
      - name: packer

    pip_packages:
      - name: sqlparse

  tasks:
    - name: homebrew update
      homebrew:
        update_homebrew: yes

    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      # ※1 GUIツールをインストールする場所を `/Application` に固定
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    - name: Pip install some packages
      pip:
        name='{{ item.name }}'
      with_items: '{{ pip_packages }}'

