- hosts: localhost
  connection: local

  vars:

    homebrew_cask_packages:
      - name: docker
      - name: sourcetree
      - name: iterm2
      - name: slack
      - name: google-japanese-ime
      - name: firefox
      - name: visual-studio-code
      - name: intellij-idea
      #- name: dropbox

    homebrew_packages:
      - name: zsh
      - name: zsh-syntax-highlighting
      - name: zsh-completions
      - name: git
      - name: git-lfs
      - name: tree
      - name: nkf
      - name: sqlite
      - name: wget
      - name: jq
      - name: github/gh/gh
      - name: vim
      - name: tig
      - name: ghq
      - name: peco
      - name: packer
      - name: azure-cli
      - name: kotlin
      - name: gradle

    pip_packages:
      - name: sqlparse
    
    node_packages:
      - name: express

  tasks:
    - name: homebrew update/upgrade
      # brew updateはHomebrewのアップデートのみ行うのに対して、brew upgradeではHomebrewのアップデートに加えてHomebrewでインストールしたパッケージのアップデートも行う
      homebrew:
        update_homebrew: yes
        upgrade_all: yes

    - name: homebrew cask packages install
      homebrew_cask: name={{ item.name }} state=installed
      # ※1 GUIツールをインストールする場所を `/Application` に固定
      environment:
        HOMEBREW_CASK_OPTS: "--appdir=/Applications"
      with_items: '{{ homebrew_cask_packages }}'

    - name: homebrew packages install
      homebrew:
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
      with_items: '{{ homebrew_packages }}'

    - name: Python 3.8 install some packages (not virtualenv)
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pip_module.html
      pip:
        name: '{{ item.name }}'
        executable: pip3.8
      with_items: '{{ pip_packages }}'
    
    - name: Install node.js package globally.
      # https://docs.ansible.com/ansible/latest/collections/community/general/npm_module.html
      community.general.npm:
        name: '{{ item.name }}'
        global: yes
      with_items: '{{ node_packages }}'

